# Generated by Django 5.2.4 on 2025-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_image_video_videopost_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='videopost',
            name='lesson',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
