# Generated by Django 5.2.4 on 2025-08-08 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_image_delete_video_remove_article_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='lesson',
        ),
        migrations.AddField(
            model_name='videopost',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
